### ISSUE TITLE
Question: Avoid the update of gameData object when passed to players hero

### ISSUE THREAD

**Issue by gyandeeps** [JavascriptBattle/hero-starter#33]
Excellent concept and game. Kudos
 How do you check if the player has not manipulated the gameData object which you pass it to the move function? 

Just curious.

**Comment by forrestbthomas** [comment]
Hey there! Thanks for the interest.
The short answer is that we run the users code on a server in an isolated environment that sends back the response of that function (which is supposed to be a string 'North', 'South', etc). That response is then used to update the actual game object on our server, which is then passed to the next users' isolated server. This process is repeated for each user, until the game is completed.
Thanks again for your interest and we hope you continue to enjoy the game!

**Comment by gyandeeps** [comment]
Sounds good.
Thanks
