### ISSUE TITLE
Test battle: Hero "stuck" between objects

### ISSUE THREAD

**Issue by TimKam** [JavascriptBattle/hero-starter#34]
In a recent test battle, my hero had a starting position where he was stuck between objects (mine, bushes and health well) and thus could only move to one other tile:
![jsbattlebug](https://cloud.githubusercontent.com/assets/5434565/4627977/455d7cc0-5391-11e4-99e3-9d385e70dd04.png)

I guess this is a bug and applies to the "real" game as well.

Edit: Sorry for posting this here, although it probably belongs into one of the other JavaScript battle projects.

**Comment by forrestbthomas** [comment]
Oh, interesting. One of the side effects of creating a randomized map, I suppose. =) We are working on adding a feature to the test site where you can choose a predefined map that would be used in the 'real' game. This scenario would only happen in the 'real' game if you are trapped by an enemy whose code is not working properly, which can happen. 
In the meantime, just click the simulate game button again for a new map if this scenario happens again. 
Thanks for the interest!
