### ISSUE TITLE
Code Works on Test Site, Not in Game

### ISSUE THREAD

**Issue by allknowingfrog** [JavascriptBattle/hero-starter#39]
This is a really awesome concept, but I can't seem to get started. My code runs correctly when I upload it to the test site, but my hero hasn't made a move since I signed up a few days ago. I believe I followed the steps correctly. I forked the repo and have double-checked that the repo name is correct in my profile on the javascriptbattle site. Are there any other obvious things I might be overlooking?

**Comment by robertpdx** [comment]
EDIT: Disregard my previous comment.  The current version looks like yours...

**Comment by allknowingfrog** [comment]
I found the issue. I build my own tile array to follow a more standard (x,y) coordinate system with my helper functions. It worked on the test site, but not in the game, because of how I referenced my hero's tile.
